# Literature Review  

Wind speeds may be categorized as dangerous once reaching the threshold of 50mph. Winds of this caliber may occur during sorms and tornados, and can be catastrophic to infrastructure. 

Structurally, windows are weak in comparison to the surrounding structure and therefore are generally the first to break when confronted with strong winds. The missing window then creates a cavity with a pressure differential to the outside wind that may encourage further destruction. The fragility of windows is why many coastal buildings near hurricane hotspots have shutters, and in the event of a storm, those without shutters often cover their windows with materials such as plywood to protect against the oncoming winds. 

The average home is designed to withstand winds of 90mph for around 3 seconds, which is far from sufficient to withstand even a moderate class of tornado. Especially when including forces working in tadem generating lift on top of normal stressors. As roof connections rely primarily on gravity to ensure stabiity, any opposing force to gravity need only overcome the weight force of the roof to remove it from the structure entirely.

Due to the propensity of air to create vortices when exposed to nonzero velocity and pressure differential, the way air may travel through the structure could pose an additional destructor on top of the exterior conditions. It has been proven advantageous for homes in storm-prone areas to install shutters, so prevention of inducing cavity-like flow on a structure is of import.


Citations:
  Hadhazy, A. (2022, March 11). How a tornado can destroy a house. Popular Mechanics. Retrieved May 14, 2022, from https://www.popularmechanics.com/adventure/outdoors/a6723/gone-in-four-seconds-how-a-tornado-destroys-a-house/ 
  How high does wind speed need to be to damage a home? Super Inspection Pros. (2020, August 11). Retrieved May 14, 2022, from https://superinspectionpros.com/blog/how-high-does-wind-speed-need-to-be-to-damage-a-home/ 
  Tessner, T., Author:&nbsp;Tommy Tessner	https://eurexshutters.com/author/tommytessner/ Tommy Tessner is the Vice president of Eurex Shutters, Author: &amp; Tommy Tessner is the Vice president of Eurex Shutters. (2022, April 12). What are hurricane shutters? an introduction to hurricane shutters. Eurex Shutters. Retrieved May 14, 2022, from https://eurexshutters.com/what-are-hurricane-shutters/ 
